//
// Created by Weiping Huang on 2015/11/25.
//

#ifndef LEETCODE__0106_CONSTRUCT_BINARY_TREE_FROM_INORDER_AND_POSTORDER_TRAVERSAL_H
#define LEETCODE__0106_CONSTRUCT_BINARY_TREE_FROM_INORDER_AND_POSTORDER_TRAVERSAL_H


class _0106_Construct_Binary_Tree_from_Inorder_and_Postorder_Traversal {



};


#endif // LEETCODE__0106_CONSTRUCT_BINARY_TREE_FROM_INORDER_AND_POSTORDER_TRAVERSAL_H
