//
// Created by Weiping Huang on 2015/11/25.
//

#ifndef LEETCODE__0128_LONGEST_CONSECUTIVE_SEQUENCE_H
#define LEETCODE__0128_LONGEST_CONSECUTIVE_SEQUENCE_H


class _0128_Longest_Consecutive_Sequence {



};


#endif // LEETCODE__0128_LONGEST_CONSECUTIVE_SEQUENCE_H
