//
// Created by Weiping Huang on 2015/11/25.
//

#ifndef LEETCODE__0159_LONGEST_SUBSTRING_WITH_AT_MOST_TWO_DISTINCT_CHARACTERS_H
#define LEETCODE__0159_LONGEST_SUBSTRING_WITH_AT_MOST_TWO_DISTINCT_CHARACTERS_H


class _0159_Longest_Substring_with_At_Most_Two_Distinct_Characters {



};


#endif // LEETCODE__0159_LONGEST_SUBSTRING_WITH_AT_MOST_TWO_DISTINCT_CHARACTERS_H
