//
// Created by Weiping Huang on 2015/11/25.
//

#ifndef LEETCODE__0158_READ_N_CHARACTERS_GIVEN_READ4_II___CALL_MULTIPLE_TIMES_H
#define LEETCODE__0158_READ_N_CHARACTERS_GIVEN_READ4_II___CALL_MULTIPLE_TIMES_H


class _0158_Read_N_Characters_Given_Read4_II___Call_multiple_times {



};


#endif // LEETCODE__0158_READ_N_CHARACTERS_GIVEN_READ4_II___CALL_MULTIPLE_TIMES_H
