//
// Created by Weiping Huang on 2015/11/25.
//

#ifndef LEETCODE__0255_VERIFY_PREORDER_SEQUENCE_IN_BINARY_SEARCH_TREE_H
#define LEETCODE__0255_VERIFY_PREORDER_SEQUENCE_IN_BINARY_SEARCH_TREE_H


class _0255_Verify_Preorder_Sequence_in_Binary_Search_Tree {



};


#endif // LEETCODE__0255_VERIFY_PREORDER_SEQUENCE_IN_BINARY_SEARCH_TREE_H
