//
// Created by Weiping Huang on 2015/11/25.
//

#ifndef LEETCODE__0270_CLOSEST_BINARY_SEARCH_TREE_VALUE_H
#define LEETCODE__0270_CLOSEST_BINARY_SEARCH_TREE_VALUE_H


class _0270_Closest_Binary_Search_Tree_Value {



};


#endif // LEETCODE__0270_CLOSEST_BINARY_SEARCH_TREE_VALUE_H
