//
// Created by Weiping Huang on 2015/11/25.
//

#ifndef LEETCODE__0298_BINARY_TREE_LONGEST_CONSECUTIVE_SEQUENCE_H
#define LEETCODE__0298_BINARY_TREE_LONGEST_CONSECUTIVE_SEQUENCE_H


class _0298_Binary_Tree_Longest_Consecutive_Sequence {



};


#endif // LEETCODE__0298_BINARY_TREE_LONGEST_CONSECUTIVE_SEQUENCE_H
